Hasaki/Areas/Admin/Controllers/LoginRegisController.cs
using Hasaki.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Hasaki.Areas.Admin.Controllers
{
    public class LoginRegisController : Controller
    {
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(NhanVien nv)
        {
            var db = new HasakiDatabaseEntities1();
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(nv.TenDangNhap))
                    ModelState.AddModelError(string.Empty, "Email không được để trống");
                if (string.IsNullOrEmpty(nv.MatKhau))
                    ModelState.AddModelError(string.Empty, "Mật khẩu không được để trống");
                if (ModelState.IsValid)
                {
                    var nhanvien = db.NhanViens.FirstOrDefault(k => k.TenDangNhap == nv.TenDangNhap && k.MatKhau.ToLower() == nv.MatKhau.ToLower());
                    if (nhanvien != null)
                    {
                        Session["Name"] = nhanvien.TenNhanVien;
                        Session["IDuser"] = nhanvien.VaiTro;
                    }
                    else
                    {
                        var mail = db.NhanViens.FirstOrDefault(k => k.TenDangNhap == nv.TenDangNhap);
                        if (mail != null)
                        {
                            ModelState.AddModelError(string.Empty, "Sai mật khẩu");
                            return View();
                        }
                        ModelState.AddModelError(string.Empty, "Tài khoản không tồn tại");
                        return View();
                    }
                }
            }
            return RedirectToAction("DanhSachDH", "DonHang");
        }
    }
}

Hasaki/Areas/Admin/Views/LoginRegis/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hasaki Admin Login</title>

    <link href="~/Areas/AdminContent/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="~/Areas/AdminContent/css/sb-admin-2.css" rel="stylesheet" />

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <!-- Nested Row within Card Body -->
                    <div>
                        @using (Html.BeginForm("Login", "LoginRegis"))
                        {
                            <div>
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            @Html.TextBox("TenDangNhap", null, new
                                            {
                                                @class = "form-control form-control-user",
                                                @id = "email",
                                                @placeholder = "Nhập tài khoản...",
                                                @type = "text",
                                                @aria_describedby = "emailHelp",
                                                required = "required"
                                            })
                                        </div>
                                        <div class="form-group">
                                            @Html.Password("MatKhau", null, new
                                            {
                                                @class = "form-control form-control-user",
                                                @id = "pass",
                                                @placeholder = "Password",
                                                @type = "password",
                                                required = "required"
                                            })
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </button>
                                        <hr>
                                    </form>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>